### ISSUE TITLE
It seems that some tags are a bit cooked. Look at the Logs for more Info if certain Functions are broken.

### ISSUE THREAD

**Issue by GoldenFurredFox** [Dragon-Seeker/LoadMyFuckingTags#3]
Fabric version 0.14.21 for Minecraft 1.20.1
LMFT version 1.0.1

My [latest.log](https://github.com/Dragon-Seeker/LoadMyFuckingTags/files/11967636/latest.log) for your convenience. Also available as a [GitHub Gist](https://gist.github.com/Lxndwich/30a80e4de35f8b48c7a9911a6cbb711b).

**Comment by GoldenFurredFox** [comment]
As a side note; your Issues page isn't directly linked from [CurseForge](https://www.curseforge.com/minecraft/mc-mods/lmft), though you did link it properly from [Modrinth](https://modrinth.com/mod/lmft), which is good.

**Comment by Dragon-Seeker** [comment]
Thanks for informing me of the mixup. The error refers to some broken tags and the chat message is just an indicator that you should check the logs of the server you are connecting to precisely. If you are not a mod or mod pack dev, then you can mostly not care about it.

Ill see about adding a link for more info and maybe changing the color to yellow to make it less of error and more a warning.

**Comment by Dragon-Seeker** [comment]
Since there hasn't been much response to this, I am closing it but you can read thru the Info File to get a understand of the problem or a way of silencing the message: [Link](https://github.com/Dragon-Seeker/LoadMyFuckingTags/blob/Multi-Loader-1.20.x/common/src/main/java/io/wispforest/lmft/LMFTCommon.java)
