### ISSUE TITLE
[1.20.1 Forge] Latest update causese crash with "Yeetus Experimentus".

### ISSUE THREAD

**Issue by PlayfulPiano** [Dragon-Seeker/LoadMyFuckingTags#9]
https://github.com/nanite/Yeetus-Experimentus/issues/3

**Comment by Dragon-Seeker** [comment]
Such an update is only related to Forge API Versions 47.2.6 and higher due to a change within the Patch for Tagloading. This leads to the mixin crashing due to such. The Patch notes reflect such a warning but I did leave out editing the toml which is a minor oversight. 

Please downgrade the version as such is not required and the 1.0.3 release should be fine for the given forge version

**Comment by Dragon-Seeker** [comment]
I've made sure to reupload the jar with proper forge API version restrictions to prevent headaches to why such is crashing which should have been done but forgot
